In [1]:
!pip install ucimlrepo

Requirement already satisfied: ucimlrepo in C:\Users\HomePC\.venv\Lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in C:\Users\HomePC\.venv\Lib\site-packages (from ucimlrepo) (3.0.3)
Requirement already satisfied: certifi>=2020.12.5 in C:\Users\HomePC\.venv\Lib\site-packages (from ucimlrepo) (2026.6.17)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\HomePC\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HomePC\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HomePC\.venv\Lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\HomePC\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder,
    PolynomialFeatures
)
from sklearn.impute import SimpleImputer

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    LogisticRegression
)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [3]:
forest_fires = fetch_ucirepo(id=162)

X = forest_fires.data.features
y = forest_fires.data.targets

print("Features:")
display(X.head())

print("\nTarget:")
display(y.head())

Features:

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0

Target:

   area
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0

In [5]:
print(X.info())

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    str
 3   day     517 non-null    str
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
dtypes: float64(7), int64(3), str(2)
memory usage: 48.6 KB
None

In [6]:
print(X.describe(include="all"))

                 X           Y month  day        FFMC         DMC          DC  \
count   517.000000  517.000000   517  517  517.000000  517.000000  517.000000
unique         NaN         NaN    12    7         NaN         NaN         NaN
top            NaN         NaN   aug  sun         NaN         NaN         NaN
freq           NaN         NaN   184   95         NaN         NaN         NaN
mean      4.669246    4.299807   NaN  NaN   90.644681  110.872340  547.940039
std       2.313778    1.229900   NaN  NaN    5.520111   64.046482  248.066192
min       1.000000    2.000000   NaN  NaN   18.700000    1.100000    7.900000
25%       3.000000    4.000000   NaN  NaN   90.200000   68.600000  437.700000
50%       4.000000    4.000000   NaN  NaN   91.600000  108.300000  664.200000
75%       7.000000    5.000000   NaN  NaN   92.900000  142.400000  713.900000
max       9.000000    9.000000   NaN  NaN   96.200000  291.300000  860.600000

               ISI        temp          RH        wind        rain
count   517.000000  517.000000  517.000000  517.000000  517.000000
unique         NaN         NaN         NaN         NaN         NaN
top            NaN         NaN         NaN         NaN         NaN
freq           NaN         NaN         NaN         NaN         NaN
mean      9.021663   18.889168   44.288201    4.017602    0.021663
std       4.559477    5.806625   16.317469    1.791653    0.295959
min       0.000000    2.200000   15.000000    0.400000    0.000000
25%       6.500000   15.500000   33.000000    2.700000    0.000000
50%       8.400000   19.300000   42.000000    4.000000    0.000000
75%      10.800000   22.800000   53.000000    4.900000    0.000000
max      56.100000   33.300000  100.000000    9.400000    6.400000

In [7]:

print("\nTarget information:")
print(y.info())
print(y.describe())

Target information:
<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    517 non-null    float64
dtypes: float64(1)
memory usage: 4.2 KB
None
              area
count   517.000000
mean     12.847292
std      63.655818
min       0.000000
25%       0.000000
50%       0.520000
75%       6.570000
max    1090.840000